title: Mumu
email: gugusine773@gmail.com
description: >- # 用于 SEO
  A personal workspace for casual notes on machine learning and something else.
baseurl: "" # 这里的如果是根目录则留空
url: "" 
github_username: illusionsin30 # 替换为你的 GitHub 用户名
repository: illusionsin30/illusionsin30.github.io # 用于获取 Branch 信息

# Build settings
markdown: kramdown
theme: null # 因为我们是手动写 layout，这里设为 null 或注释掉
kramdown:
  input: GFM
  syntax_highlighter: rouge

# 这一步不是必须的，但如果你的代码块没有颜色，尝试添加这个
highlighter: rouge

# 插件（GitHub Pages 支持）
plugins:
  - jekyll-seo-tag
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"